// 'use client';

// import { useState } from 'react';
// import Footer from './components/Footer';
// import HomeNavbar from './components/HomeNavbar';
// import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import MainAll from './components/MainAll/MainAll';
// import { useInView } from 'react-intersection-observer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const { ref, inView } = useInView({
  //   /* Optional options */
  //   threshold: 0,
  // })
  // console.log(inView)
  // const [show , setShow] = useState(false)


  return (
    <html lang="en">
      
      <body className={inter.className}>
        <MainAll children={children}></MainAll>
      </body>
    </html>
  )
}
